import{a as b,i as l,S as L}from"./assets/vendor-6e0bf343.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();function p(t){return t.map(({webformatURL:r,tags:a,largeImageURL:o,likes:e,views:s,comments:n,downloads:u})=>` <li class="gallery-item">
        <a class="gallery-link" href="${o}" >
          <img class="gallery-image"
           src="${r}" 
           alt="${a}" 
           width = "360"/>
          <ul class="card-descr">
           <li class="card-element"><span class="label">Likes</span> <p class ="value">${e}</p></li>
            <li class="card-element"><span class="label">Views</span> <p class ="value">${s}</p></li>
            <li class="card-element"><span class="label">Comments</span> <p class ="value">${n}</p></li>
            <li class="card-element"><span class="label">Downloads</span><p class ="value">${u}</p></li></ul>
        </a>
      </li>`).join("")}const w="43193709-9f2e77a8cd9049868dd3fabee";async function m(t,r="1"){const a={key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:15};try{const o=await b.get("https://pixabay.com/api/",{params:a});if(o.status!==200)throw new Error(o.statusText);return o.data}catch(o){throw o}}const g=document.querySelector(".search-form"),c=document.querySelector(".gallery"),C=document.querySelector(".search-btn"),f=document.querySelector(".loader"),i=document.querySelector(".load-more");i.addEventListener("click",v);C.addEventListener("click",y);g.addEventListener("submit",y);let d=1;function h(){f.style.display="block"}function S(){f.style.display="none"}function y(t){t.preventDefault();const a=document.querySelector(".search-form input").value.trim();if(a===""){l.show({message:"Please enter a search query",messageColor:" #fff",backgroundColor:"#ef4040",position:"topCenter",messageSize:"16px",messageLineHeight:"150%",iconColor:"white"});return}h(),c.innerHTML="",m(a).then(o=>{if(o.hits.length===0)l.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:" #fff",backgroundColor:"#ef4040",position:"topCenter",messageSize:"16px",messageLineHeight:"150%",iconColor:"white"});else{c.innerHTML=p(o.hits);const e={captionDelay:250,captionsData:"alt",captionPosition:"bottom"};new L(".gallery a",e).refresh();const n=15,u=Math.ceil(o.total/n);d<u&&i.classList.replace("load-hidden","load-more")}}).catch(o=>{c.innerHTML="",l.show({message:"An error occurred while fetching images. Please try again later.",messageColor:" #fff",backgroundColor:"#ef4040",position:"topCenter",messageSize:"16px",messageLineHeight:"150%",iconColor:"white"})}).finally(()=>{S(),g.reset()})}async function v(){h(),i.disabled=!0;try{d++;const t=await m(d);t&&t.hits&&t.hits.length>0?(c.insertAdjacentHTML("beforeend",p(t.hits)),i.disabled=!1,t.page>=t.totalPages&&(i.classList.replace("load-more","load-hidden"),l.show({message:"We're sorry, but you've reached the end of search results.",messageColor:"#fff",backgroundColor:"#ef4040",position:"topCenter",messageSize:"16px",messageLineHeight:"150%",iconColor:"white"}),i.remove())):i.style.display="none"}catch(t){console.error("Error loading more images",t)}}function x(){const t=document.querySelector(".gallery a");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}x();
//# sourceMappingURL=commonHelpers.js.map
